export const GET_CATS_START = 'GET_CATS_START';
export const GET_CATS_SUCCESS = 'GET_CATS_SUCCESS';
export const GET_CATS_FAILURE = 'GET_CATS_FAILURE';

export const GET_CAT_DETAILS = 'GET_CAT_DETAILS';
export const GET_CAT_DETAILS_SUCCESS = 'GET_CAT_DETAILS_SUCCESS';
export const GET_CAT_DETAILS_FAILURE = 'GET_CAT_DETAILS_FAILURE';

export const RESET_SEELECTED_CAT_OBJECT='RESET_SEELECTED_CAT_OBJECT'

export const GET_CATS_AFTER_SEARCH='GET_CATS_AFTER_SEARCH'

export const REFRESH_PAGE='REFRESH_PAGE'

export const GET_CATS_AFTER_REFRESH='GET_CATS_AFTER_REFRESH'